import frappe

def execute():
    roles = [
        # ✅ Existing 25 roles you already added
        "Trainer",
        "Trainer Head",
        "Procurement User",
        "Branch Manager",
        "Cluster Manager",
        "Regional Manager",
        "Zonal Manager",
        "Audit Member",
        "Audit Manager",
        "Email Creator",
        "Team Leader - BOM",
        "BD-others",
        "IT Support Executive",
        "Admin Support Executive",
        "Operations Support Executive",
        "HR Support Executive",
        "Accounts Support Executive",
        "HO Support Executive",
        "Facility Support Executive",
        "Loan Support Executive",
        "Circular Manager",
        "Team Leader - DDS",
        "Team Leader - SMBG",
        "BDOs",
        "BDEs",
        "ticket cancel user",
        "CBS Support Executive",
        "CBS Support Manager",

        # ✅ Remaining 107 roles (no duplicates)
        "AGM",
        "Academics User",
        "Accounts Executive",
        "Accounts Manager",
        "Accounts Support Manager",
        "Accounts User",
        "Admin Executive",
        "Admin Store Executive",
        "Admin Store Manager",
        "Admin Support Manager",
        "Administrator",
        "All",
        "Analytics",
        "Asset List Customizer",
        "BDO & BDE",
        "Blogger",
        "CEO",
        "CFO",
        "CTO",
        "Customer",
        "Dashboard Manager",
        "Desk User",
        "DH User",
        "email tester",
        "Employee",
        "Employee Self Service",
        "Executive",
        "Expense Approver",
        "Facility",
        "Facility Support Manager",
        "Fleet Manager",
        "Fulfillment User",
        "GMHR",
        "Guest",
        "HO HOD",
        "HO asst. HOD",
        "HO Support Manager",
        "HR Executive",
        "HR Manager",
        "HR Support Head",
        "HR Support Manager",
        "HR User",
        "HRM HO",
        "HRM RO",
        "HRM ZO",
        "Inbox User",
        "Interviewer",
        "Item Manager",
        "IT Asset Admin",
        "IT Manager",
        "IT Senior Manager",
        "IT Store Executive",
        "IT Store Manager",
        "IT Support Manager",
        "JLL Executive",
        "JLL Manager",
        "Knowledge Base Contributor",
        "Knowledge Base Editor",
        "Leave Approver",
        "Loan Executive",
        "Loan Manager",
        "Loan Support Manager",
        "Maintenance Manager",
        "Maintenance User",
        "Manufacturing Manager",
        "Manufacturing User",
        "MIS",
        "MIS Admin",
        "MIS Executive",
        "MIS User",
        "Newsletter Manager",
        "Operations Co-Ordinator",
        "Operations Executive",
        "Operations HOD",
        "Operations Support Manager",
        "Prepared Report User",
        "Projects Manager",
        "Projects User",
        "Purchase Department",
        "Purchase Manager",
        "Purchase Master Manager",
        "Purchase Store Executive",
        "Purchase Store Manager",
        "Purchase User",
        "Quality Manager",
        "Report Manager",
        "RM_role",
        "Sahayog System Admin",
        "Sales Manager",
        "Sales Master Manager",
        "Sales User",
        "Script Manager",
        "Share Admin",
        "Share Executive",
        "Share User",
        "Stationery Asset Admin",
        "Stationery Store & Support Manager",
        "Stationery Store Executive",
        "Stationery Store Manager",
        "Stock Manager",
        "Stock User",
        "Store Manager",
        "Support Team",
        "Supplier",
        "System Manager",
        "Translator",
        "user891",
        "Website Manager",
        "Workspace Manager"
    ]

    for role in roles:
        if not frappe.db.exists("Role", role):
            frappe.get_doc({
                "doctype": "Role",
                "role_name": role,
                "desk_access": 1
            }).insert(ignore_permissions=True)
