import frappe
from frappe.utils import getdate


LEAVE_TYPES = [
    ("Balance SL", "Sick Leave"),
    ("Balance CL", "Casual Leave"),
    ("Balance EL", "Earned Leave"),
]


def execute():
    from frappe.utils import nowdate, getdate

    today = getdate(nowdate())
    created = 0
    skipped = 0
    not_found = []

    data = get_data()

    for row in data:
        emp_name = row["name"]
        balances = {"Sick Leave": row["sl"], "Casual Leave": row["cl"], "Earned Leave": row["el"]}

        if all(v == 0 for v in balances.values()):
            skipped += 1
            continue

        emp_name_search = emp_name.strip().upper()

        emp = frappe.db.get_value(
            "Employee",
            {"employee_name": ["like", f"%{emp_name_search}%"], "custom_is_support_staff": 1},
            ["name", "employee_name", "date_of_joining", "status"],
            as_dict=True,
        )

        if not emp:
            first_word = emp_name_search.split()[0]
            emp = frappe.db.get_value(
                "Employee",
                {"employee_name": ["like", f"%{first_word}%"], "custom_is_support_staff": 1},
                ["name", "employee_name", "date_of_joining", "status"],
                as_dict=True,
            )

        if not emp:
            not_found.append(emp_name)
            print(f"NOT FOUND: {emp_name}")
            continue

        doj = emp.date_of_joining or "2026-01-01"

        for db_col, lt_name in LEAVE_TYPES:
            bal = balances[lt_name]
            if bal <= 0:
                continue

            existing_name = frappe.db.get_value(
                "Leave Allocation",
                {
                    "employee": emp.name,
                    "leave_type": lt_name,
                    "from_date": doj,
                    "to_date": "2026-12-31",
                    "docstatus": 1,
                },
            )
            if existing_name:
                existing_doc = frappe.get_doc("Leave Allocation", existing_name)
                if existing_doc.new_leaves_allocated == bal:
                    print(f"UNCHANGED: {emp.employee_name} - {lt_name} = {bal}")
                    continue
                existing_doc.cancel()
                print(f"CANCELLED: {emp.employee_name} - {lt_name} (was {existing_doc.new_leaves_allocated})")

            alloc = frappe.get_doc(
                {
                    "doctype": "Leave Allocation",
                    "employee": emp.name,
                    "leave_type": lt_name,
                    "from_date": doj,
                    "to_date": "2026-12-31",
                    "new_leaves_allocated": bal,
                    "carry_forward": 0,
                }
            )
            try:
                alloc.insert(ignore_permissions=True)
                alloc.submit()
                created += 1
                print(f"ALLOCATED: {emp.employee_name} - {lt_name} = {bal}")
            except Exception as e:
                if "OverlapError" in type(e).__name__:
                    print(f"SKIP (overlap): {emp.employee_name} - {lt_name}")
                else:
                    raise

    print(f"\nDone! Allocations created: {created}, Skipped (zero): {skipped}")
    if not_found:
        print(f"\nNot found ({len(not_found)}):")
        for n in not_found:
            print(f"  - {n}")
    frappe.db.commit()


def get_data():
    return [
        {"name": "PANCHSHILA WAHANE", "sl": 3.5, "cl": 4, "el": 14},
        {"name": "PRAMITA WAHANE", "sl": 2.5, "cl": 4, "el": 20},
        {"name": "SHRIKANT GANESH SHIVANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANISHA D NANDURKAR", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "BEBI M KOLHE", "sl": 8.5, "cl": 4, "el": 22},
        {"name": "RINA VINAYAK MESHRAM", "sl": 4.5, "cl": 2, "el": 27},
        {"name": "LATA RAJU SAPATE", "sl": 1.5, "cl": 3, "el": 15},
        {"name": "NISHA V BHASMOTE", "sl": 6.5, "cl": 4, "el": 23},
        {"name": "GUNWANTA G BHOYAR", "sl": 1.5, "cl": 1, "el": 21},
        {"name": "JYOTI S NAGPURE", "sl": 6.5, "cl": 4, "el": 30},
        {"name": "RANJANA V PATIL", "sl": 2.5, "cl": 1.5, "el": 8},
        {"name": "VANDANA CHACHANE", "sl": 3.5, "cl": 1.5, "el": 10},
        {"name": "SHILPA VINAYAK GONDANE", "sl": 2.5, "cl": 3.5, "el": 11},
        {"name": "HARSHA NEHARE", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "SINDHU S PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "USHA SUNIL DESHBHRATAR", "sl": 1.5, "cl": 1.5, "el": 4},
        {"name": "JAISHREE PARTEKI", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "ARUNA A DESHBHRATAR", "sl": 1.5, "cl": 1, "el": 3},
        {"name": "MADHURI D SALAME", "sl": 6.5, "cl": 4, "el": 20},
        {"name": "SANDHYA PUSADKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHETAN S JADHAV", "sl": 0, "cl": 0, "el": 0},
        {"name": "DHANASHREE MESHRAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "TINA KHOBRAGADE", "sl": 6.5, "cl": 4, "el": 24},
        {"name": "MANISHA TIGHARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DINESH TEKAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUDHIR SEVAKRAM CHAUDHARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "UMESH ARUN SALAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRASHANT B. SONTAKKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SURESH BAMBORDE", "sl": 7.5, "cl": 4, "el": 30},
        {"name": "DINESH M. KUMBHARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAPANA D RAUT", "sl": 5.5, "cl": 4, "el": 16},
        {"name": "ASHA MADAN BAMBOLE", "sl": 2, "cl": 0.5, "el": 2.5},
        {"name": "OM JIVAN KALYANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "KHAIRUNNISHA KURESHI", "sl": 1.5, "cl": 1.5, "el": 7},
        {"name": "KANTA KESHAV RAUT", "sl": 5.5, "cl": 4, "el": 19},
        {"name": "YOGESHWARI SURESH MASKARE", "sl": 2.5, "cl": 2.5, "el": 9},
        {"name": "VISHAL YASHVANT KHANDARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VIJAY VASANTRAO MORE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHALU PANDURANGJI CHANNE", "sl": 5.5, "cl": 4, "el": 23},
        {"name": "HEMLATA PRASAD KHAPEKAR", "sl": 8.5, "cl": 4, "el": 23},
        {"name": "YASH MOHANRAO KHADSE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUNNY SALVE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAHUL DHOBALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "KAVITA RAVI BEDARKAR", "sl": 4.5, "cl": 4, "el": 15},
        {"name": "SUCHITA D RANGARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHIVA LANDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RITIK S BURCHUNDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NITA GANESH WADODE", "sl": 4.5, "cl": 4, "el": 27},
        {"name": "CHHANNU H SEUTKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "VANDANA M MADAVI", "sl": 1.5, "cl": 2, "el": 12},
        {"name": "PRAGATI ANIL MESHRAM", "sl": 1.5, "cl": 1.5, "el": 17},
        {"name": "DHANANJAY RAMBHAU SHELKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANITA ARUN KHOTE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SATISH DATTATREY CHAUDHARY", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAJHANS LAXMIKANT JOSHI", "sl": 0, "cl": 0, "el": 0},
        {"name": "KUNAL RAMESH ROKDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANIKET VIJAY CHAVHAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHETAN WAVARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINOD PARSHURAM THAKUR", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAPANA ZURMURE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINOD BALIRAM RATHOD", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANIL KESHAV GHUGE", "sl": 0, "cl": 0, "el": 0},
        {"name": "TRISHUL DAKKHANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "JYOTI DIGAMBER KSHIRSAGAR", "sl": 6.5, "cl": 4, "el": 27},
        {"name": "RAJESH VIDHATE", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "PADMBHUSHAN BABURAO UMEKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "ROSHANI MANOHAR KHODE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SWAPNIL RAJU MANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "KUNAL DIPAK TODDSAM", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "SARIKA AVINASH BABHARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RINA MANGARU NAITAM", "sl": 2.5, "cl": 4, "el": 28},
        {"name": "YASH DIVAKAR INGALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SADHANA DATTU BHOYAR", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "MANJUSHA CHALURKAR", "sl": 4.5, "cl": 4, "el": 30},
        {"name": "ASHWINI MAROTI SHRIRAME", "sl": 0, "cl": 0, "el": 0},
        {"name": "GANESH DNYANESHWAR TELANGE", "sl": 4.5, "cl": 4, "el": 30},
        {"name": "VAISHALI VIJAY HIWRALE", "sl": 0.5, "cl": 0.5, "el": 2},
        {"name": "SHUBHANGI DESHBRATAR", "sl": 3.5, "cl": 2, "el": 21},
        {"name": "TUSHAR T. SHENDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DASHRATH BHAIYYALAL BANSOD", "sl": 0, "cl": 0, "el": 0},
        {"name": "DINESH BHIMRAO VANJARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRANAY SURESH HIRADEVE", "sl": 0, "cl": 0, "el": 0},
        {"name": "GAVESH BHIMRAO VANJARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "NARAYAN VISHWAMBAR DAHALKE", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "PAYAL SANJAY KASWALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "LAXMAN PRALHAD SHINDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RUSHABH VIJAY MUJMULE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NIKHIL SANTOSHRAO SATAV", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "SANGITA SANTOSH BHOYAR", "sl": 3, "cl": 3.5, "el": 17},
        {"name": "SACHIN SHANKAR HEDAU", "sl": 0, "cl": 0, "el": 0},
        {"name": "VISHAL P. GANLAWAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRATIBHA PRAMOD ZILE", "sl": 7.5, "cl": 4, "el": 30},
        {"name": "AKSHAY S MUNESHWAR", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "PRADIP D VYAVHARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RANJANA VILAS LOKHANDE", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "SNEHA ANIL MEKALWAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "POOJA ANKUSH GANGASAGAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "ASHUTOSH NAVALSING INGLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VAISHALI R. MOHITE", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRATHAMESH PURUSHOTTAM SHEWANE", "sl": 0, "cl": 0, "el": 0},
        {"name": "GAURAV POTIRWAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHAYA ANIL KUKDE", "sl": 6.5, "cl": 4, "el": 28},
        {"name": "SHIVAM SANJAYRAO GIROLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NIKESH VINAYAK CHAUDHARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "VIPIN RAJDIP MANDPE", "sl": 4.5, "cl": 2.5, "el": 15},
        {"name": "AJINKYA RAJESH WAGH", "sl": 0, "cl": 0, "el": 0},
        {"name": "NISHA NITIN GOTKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "RUPALI VINOD CHIMURKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "VAISHALI SANTOSH MADAVI", "sl": 1.5, "cl": 2, "el": 16},
        {"name": "GOPAL B. PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANISHA KALE", "sl": 0.5, "cl": 1.5, "el": 3},
        {"name": "RUTIK D. DATTA", "sl": 0, "cl": 0, "el": 0},
        {"name": "ROHIT GAMBHIR KHODKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "KAVITA KISHOR GAIKWAD", "sl": 5.5, "cl": 4, "el": 25},
        {"name": "AMITA PRAFUL GADEKAR", "sl": 7.5, "cl": 4, "el": 30},
        {"name": "PRATHMESH G. GANESHKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHILPA SHRIKANT LOKHANDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRIYANKA PINTU KADAV", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "VASANT SITARAMJI BULLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANDA GAJANAN JAMBHULKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANAND SHANKAR BOBADE", "sl": 8.5, "cl": 4, "el": 30},
        {"name": "ANAND BABAN RAUT", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRITI MAYUR BURDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHUBHAM S. INGOLE", "sl": 7.5, "cl": 4, "el": 30},
        {"name": "RITESH ASHOKRAO KOTHALE", "sl": 4.5, "cl": 4, "el": 27},
        {"name": "SUMIT GHANSYAMJI DEVULKAR", "sl": 3.5, "cl": 4, "el": 20},
        {"name": "MAHESH SOLANKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DNYANESHWAR SHRIRAM TIWALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "AJAY GAJANAN KALYANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "JAYESH RAJESH KHODE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUNITA YOGESH RAMTEKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANGALA NITIN PIMPALSHENDE", "sl": 3.5, "cl": 4, "el": 26},
        {"name": "DIPALI BHARAT SONI", "sl": 5.5, "cl": 4, "el": 26},
        {"name": "AMOL D. MOHEKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAHUL NAMDEV KHANDARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "AJAY VYANKATI AYDOL", "sl": 6.5, "cl": 4, "el": 30},
        {"name": "PUSHPA SHANKAR SHENDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "BHAGWAT B TADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "GAURAV PRALHAD HARAMKAR", "sl": 6.5, "cl": 4, "el": 26},
        {"name": "CHETAN KISAN LOKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "VISHAL WAHANE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAMESHWAR KISAN NAVKAR", "sl": 4.5, "cl": 2, "el": 22},
        {"name": "KAVITA M DONGRE", "sl": 6.5, "cl": 4, "el": 19},
        {"name": "SHANKAR DASIRAM NAITAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "RATAN GAJAMAM MADAVI", "sl": 0, "cl": 0, "el": 0},
        {"name": "NIKHIL GAJANAN PACHPOL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHRIKANT R SHRAWANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "KSHITIJ KAKADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ABHISHEK SUDHAKAR MAHALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RESHMA RAMJANKHAN PATHAN", "sl": 1.5, "cl": 3, "el": 12},
        {"name": "YOGITA RAKESH MOHURLE", "sl": 7.5, "cl": 4, "el": 17},
        {"name": "VIDHYA ASHOK BOKDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ROHIT SHIVALAL CHAWARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHUBHAM HIVARE", "sl": 6.5, "cl": 4, "el": 29},
        {"name": "ATUL MADHUKARRAO AGHAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "GAURISHANKAR SITARAM HANDE", "sl": 6.5, "cl": 4, "el": 23},
        {"name": "YASH RAMKRUSHNA GANESHPURE", "sl": 3.5, "cl": 4, "el": 19},
        {"name": "SUYOG VILASRAO GUDADHE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUNIL NARAYAN JOSHI", "sl": 0, "cl": 0, "el": 0},
        {"name": "NITA TELGOTE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUNITA RAVINDRA BADAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANKUSH YOGESH MESHRAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "TANMAY GOPAL SARODE", "sl": 0, "cl": 0, "el": 0},
        {"name": "JANARDHAN KISANRAO PADOLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "BHAVESH GAJANAN JADHAV", "sl": 0, "cl": 0, "el": 0},
        {"name": "REKHA DEEPAK KAMBLE", "sl": 8.5, "cl": 4, "el": 28},
        {"name": "DIPAK RAMDAS KORDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ROHIT S WELUKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "KSHITIJ SUDHAKAR MASKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHANDA NANDLALJI BAGDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "BHAVEK SANTOSH NARALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "AMOL RAMLAL BACHXIRE", "sl": 0, "cl": 0, "el": 0},
        {"name": "MADHURI BHARAT BHANGE", "sl": 0, "cl": 0, "el": 0},
        {"name": "KESHAV DIPAK JADHAO", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHOBHA MANOHAR MESHRAM", "sl": 6.5, "cl": 4, "el": 27},
        {"name": "SANTOSH D KHAND", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRIYA AJAY PATIL", "sl": 7.5, "cl": 4, "el": 26},
        {"name": "KIRAN RAVI DANDGE", "sl": 8.5, "cl": 4, "el": 24},
        {"name": "ARVIND SANDU BANKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "ABHISHEK REHPADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DIPALI NARENDRA KENE", "sl": 0, "cl": 0, "el": 0},
        {"name": "KOMAL NITIN KAMBLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUNIL ANIL KHADSE", "sl": 2.5, "cl": 0.5, "el": 3},
        {"name": "MANOJ MESHRAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "YOGESH RAMESHWAR SURADKAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "UJWALA MADAVI", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRATIMA LANJEWAR", "sl": 1.5, "cl": 0.5, "el": 3},
        {"name": "PUSHPA DINESH BHADADKAR", "sl": 1.5, "cl": 1.5, "el": 8},
        {"name": "VAISHALI SHIVAJI CHAUDHARI", "sl": 3.5, "cl": 4, "el": 22},
        {"name": "SUNITA RAJU DHEGLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SOPAN RAGHUNATH BHOJEGAVKAR", "sl": 4.5, "cl": 3, "el": 11},
        {"name": "BABITA BAMBODE", "sl": 0, "cl": 0, "el": 0},
        {"name": "UJWALA SUNIL BHIDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ARCHANA SUBHASH KANZODE", "sl": 3.5, "cl": 4, "el": 22},
        {"name": "SAGAR ATMARAM JAMDADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SANMESH GAJENDRA DESHBHRATAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHANDRAKALA RAJESNDRA SHRIPAD", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAHIL RAJKUMAR DESHMUKH", "sl": 0, "cl": 0, "el": 0},
        {"name": "RITESH SHESHRAO AYANE", "sl": 7.5, "cl": 4, "el": 16},
        {"name": "ARCHANA SUNIL BADHE", "sl": 2.5, "cl": 4, "el": 20},
        {"name": "SHANKAR LAXMAN PAWAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRATHMESH KOLHE", "sl": 0, "cl": 0, "el": 0},
        {"name": "AMALA DAS", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRIYANKA RAUT", "sl": 6.5, "cl": 4, "el": 18},
        {"name": "KIRAN ARVIND MESHRAM", "sl": 1.5, "cl": 2, "el": 11},
        {"name": "UPENDRA MESHRAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "VIVEK GAJBHIYE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VARSHA MANOJ KHADSE", "sl": 5.5, "cl": 4, "el": 16},
        {"name": "SANTOSH KUMAR L C", "sl": 0, "cl": 0, "el": 0},
        {"name": "RADHA V", "sl": 1.5, "cl": 4, "el": 18},
        {"name": "DHIRAJ RATHOD", "sl": 4.5, "cl": 4, "el": 13},
        {"name": "GOPAL JANJAL", "sl": 0, "cl": 0, "el": 0},
        {"name": "BALAJI DHANANJAY SHELKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAGAR NIKOSE", "sl": 1.5, "cl": 3.5, "el": 14},
        {"name": "KIRAN N", "sl": 0, "cl": 0, "el": 0},
        {"name": "JOTSANA RAHUL BOMANWAR", "sl": 2.5, "cl": 4, "el": 8},
        {"name": "RANJITA NARWADE", "sl": 3.5, "cl": 2, "el": 7},
        {"name": "VINAYAKRAO UIKEY", "sl": 0, "cl": 0, "el": 0},
        {"name": "AMBIKA N", "sl": 4.5, "cl": 3, "el": 14},
        {"name": "RAVI PAWAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANGESH VASANTRAO MADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAROJ NAIKANE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINOD BHAGWANJI UIKE", "sl": 4.5, "cl": 3, "el": 17},
        {"name": "NIKESH BHAURAO AKHARE", "sl": 4.5, "cl": 4, "el": 14},
        {"name": "SHASHIKALA ANIL THAKUR", "sl": 1.5, "cl": 2.5, "el": 16},
        {"name": "CHANDABAI JADHAO", "sl": 1.5, "cl": 3, "el": 15},
        {"name": "VAIBHAV DILIP AGHAV", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUJATA RAMTEKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "REKHA BANGARE", "sl": 3.5, "cl": 4, "el": 16},
        {"name": "RUPESH SANTOSH MALI", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANOJ NANDKUMAR OHAL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SURAJ DATTATRAY HAWARE", "sl": 7.5, "cl": 4, "el": 17},
        {"name": "LALIT RAJENDRA PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANITA MOHAN RAVARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NITIN WALMIK RANDHE", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRITI PALANDURKAR", "sl": 8.5, "cl": 2, "el": 19},
        {"name": "BHIMAPPA YALLAPPA MUMMIGATTI", "sl": 6.5, "cl": 4, "el": 14},
        {"name": "CHANDPASHA MULANI", "sl": 2.5, "cl": 1, "el": 8},
        {"name": "C NAGARAJ", "sl": 1.5, "cl": 4, "el": 19},
        {"name": "NARASIMHA S", "sl": 0, "cl": 0, "el": 0},
        {"name": "MAHENDRA SUPADU BORSE", "sl": 0, "cl": 0, "el": 0},
        {"name": "HARSH RAJESH BAGADE", "sl": 5.5, "cl": 4, "el": 16},
        {"name": "PRIYANSHU LAHANU DONDE", "sl": 7.5, "cl": 4, "el": 19},
        {"name": "LATA THAKRE", "sl": 2.5, "cl": 4, "el": 16},
        {"name": "KIRAN D GULAPPANAVAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAPNA PAWAN LANJEWAR", "sl": 5.5, "cl": 4, "el": 19},
        {"name": "ASHISH SUDHIR BHALADHARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRANAY TEJRAM KAMBLE", "sl": 7.5, "cl": 4, "el": 18},
        {"name": "MAHENDRA KUNINCHAND BHOYAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAKHI DANI", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAMYA", "sl": 7.5, "cl": 3, "el": 16},
        {"name": "REKHA BHIMTE", "sl": 8.5, "cl": 4, "el": 19},
        {"name": "GOROBA AJITRAO RAYAFALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SANTOSH PRAKASH CHAVHAN", "sl": 6.5, "cl": 2, "el": 17},
        {"name": "SAGAR SHIVAJI KANADE", "sl": 1.5, "cl": 1, "el": 5},
        {"name": "JYOTI YOGRAJ GHARSELE", "sl": 1.5, "cl": 1.5, "el": 7},
        {"name": "SUJATHA MOGLANI", "sl": 4.5, "cl": 1, "el": 5},
        {"name": "VAISHALI SURYKANT BHOYAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "VISHAL BHARAT RAMTEKE", "sl": 2.5, "cl": 2, "el": 15},
        {"name": "NITESH NYAYKARE", "sl": 4.5, "cl": 3, "el": 14},
        {"name": "SHIVRAY S. WANKHEDE", "sl": 5.5, "cl": 2, "el": 15},
        {"name": "SAVITA MESHRAM", "sl": 2.5, "cl": 3.5, "el": 12},
        {"name": "PRAVIN DILIP BHONDE", "sl": 0.5, "cl": 0.5, "el": 2},
        {"name": "SIDDHARTH DABADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "GAJANAN BALKRUSHNA BORKAR", "sl": 2.5, "cl": 1, "el": 8},
        {"name": "USHA SHRIKANT REKHE", "sl": 2.5, "cl": 4, "el": 17},
        {"name": "SHIVAM VALMIK SONAWANE", "sl": 3.5, "cl": 4, "el": 15},
        {"name": "HARI SAHU", "sl": 0, "cl": 0, "el": 0},
        {"name": "AJAY CHAUHAN", "sl": 7.5, "cl": 4, "el": 14},
        {"name": "DEVDATTA GAJBHIYE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SONALI RAJENDRA BHAGAT", "sl": 0, "cl": 0, "el": 0},
        {"name": "RUSTAM BHANWAR SINGH", "sl": 4.5, "cl": 2.5, "el": 10},
        {"name": "JYOTI MADAN LAL", "sl": 3.5, "cl": 2.5, "el": 14},
        {"name": "ANJALI SANJAY", "sl": 0, "cl": 0, "el": 0},
        {"name": "NAMDEV HARICHANDRA NALKHANDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "YASHODHA R", "sl": 2.5, "cl": 3, "el": 12},
        {"name": "GANESH RAMESH KARANGI", "sl": 0, "cl": 0, "el": 0},
        {"name": "ABHISHEKH KHASHINATH BARBANDHE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAVI CHAUHAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "PRAJAKTA PAPPU BHARANE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHUBHAM PANDURANG KAMBLE", "sl": 2.5, "cl": 0.5, "el": 3},
        {"name": "GANESH SHANKAR NAGALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DATTA DILIP ZENDE", "sl": 0.5, "cl": 0.5, "el": 8},
        {"name": "VAISHALI PRAKASH MOHIJE", "sl": 4.5, "cl": 1.5, "el": 10},
        {"name": "AKSHAY GIRDHAR MALI", "sl": 1.5, "cl": 2, "el": 10},
        {"name": "RAVI PRAKASH SALVE", "sl": 4.5, "cl": 3.5, "el": 13},
        {"name": "NISHANT DESHBHRATAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "NIKITA SACHIN MISHRA", "sl": 6.5, "cl": 4, "el": 16},
        {"name": "MONIKA NYAHARKAR", "sl": 5.5, "cl": 4, "el": 16},
        {"name": "MADHURI VINOD WAGHADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ASHISH KUMAR GODIYAL", "sl": 2.5, "cl": 0.5, "el": 9},
        {"name": "ANITA JOGENDRASINGH MANTHANWAR", "sl": 5, "cl": 4, "el": 15},
        {"name": "SEEMA HALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "RITESHKUMAR HATEL", "sl": 0, "cl": 0, "el": 0},
        {"name": "TRIVENI BENGAL", "sl": 4, "cl": 3, "el": 12},
        {"name": "LAXMAN ASHOK RAUT", "sl": 0, "cl": 0, "el": 0},
        {"name": "JAYA PETRAS SASANE", "sl": 0, "cl": 0, "el": 0},
        {"name": "AKASH EKNATH CHAVAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "KAPIL KUMAR BAGHADE", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINOD KUMAR KAROSIYA", "sl": 7, "cl": 4, "el": 13},
        {"name": "KAPIL CHAUHAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHANDRAKALA R SHARNAGAT", "sl": 1, "cl": 2, "el": 2.5},
        {"name": "KANHAIYA PARMAR", "sl": 2.5, "cl": 1.5, "el": 10},
        {"name": "KULDEEP", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAHUL DATTA WADHONKAR", "sl": 3, "cl": 1, "el": 5},
        {"name": "ABHISHEK N", "sl": 0, "cl": 0, "el": 0},
        {"name": "MRUTYUNJAYA", "sl": 0.5, "cl": 1, "el": 5},
        {"name": "ANNU MALVIYA", "sl": 4, "cl": 4, "el": 15},
        {"name": "C RAMESH", "sl": 4.5, "cl": 4, "el": 11},
        {"name": "DNYANESHWAR SHIVAJI JADHAV", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINODKUMAR KADARAMANDALAGI", "sl": 0, "cl": 0, "el": 0},
        {"name": "AMOL RAKSHAK", "sl": 0, "cl": 0, "el": 0},
        {"name": "NISHANT KOHANE", "sl": 2, "cl": 1, "el": 6},
        {"name": "SHUBHAM", "sl": 3.5, "cl": 1.5, "el": 5},
        {"name": "PRASHANT DHOLPURE", "sl": 0, "cl": 0, "el": 0},
        {"name": "JITENDRA MOURYA", "sl": 0, "cl": 0, "el": 0},
        {"name": "VINOD A. PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "AKASH SAKTEL", "sl": 0, "cl": 0, "el": 0},
        {"name": "ARCHANA B", "sl": 0, "cl": 0, "el": 0},
        {"name": "AKASH PORPAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "BABU WAGALGAVR", "sl": 3, "cl": 4, "el": 15},
        {"name": "MAYUR SANGARE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ROHIT SINGH RAJPUT", "sl": 0, "cl": 0, "el": 0},
        {"name": "CHETAN KALE", "sl": 3.5, "cl": 4, "el": 12},
        {"name": "CHANNU LAL RAJAK", "sl": 4, "cl": 2, "el": 7},
        {"name": "RANJEET SINGH", "sl": 0, "cl": 0, "el": 0},
        {"name": "HEMRAJ THAPA", "sl": 0, "cl": 0, "el": 0},
        {"name": "SARASWATI", "sl": 8, "cl": 4, "el": 15},
        {"name": "VIVEK MALVI", "sl": 3, "cl": 4, "el": 10},
        {"name": "KULDIP UDDHAVARAV WAHURWAGH", "sl": 4, "cl": 2, "el": 7},
        {"name": "HEMA KUMARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "RITU CHAMKEL", "sl": 1.5, "cl": 2.5, "el": 6},
        {"name": "SUSHMA CHANDULAL SHENDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "JAYESH KHARE", "sl": 5, "cl": 4, "el": 15},
        {"name": "ASHA SURAJ CHACHANE", "sl": 2, "cl": 3, "el": 14},
        {"name": "PUSHPA LILHARE", "sl": 3, "cl": 4, "el": 10},
        {"name": "SANDEEP MOHAN JAGDHANE", "sl": 2.5, "cl": 2.5, "el": 12},
        {"name": "RAVINDRA SINGH", "sl": 7.5, "cl": 4, "el": 14},
        {"name": "RADHA SUNIL BHENDE", "sl": 1.5, "cl": 0.5, "el": 5},
        {"name": "ASHA FIROZ KHAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "SANDHYA", "sl": 0, "cl": 0, "el": 0},
        {"name": "SANDIP SONAJI ZORE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUBHASH SHANKARRAO MATRE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ANURAG SHRIVASTAV", "sl": 0, "cl": 0, "el": 0},
        {"name": "VIDYA KANZODE", "sl": 5.5, "cl": 2, "el": 14},
        {"name": "VINOD PAL", "sl": 0, "cl": 0, "el": 0},
        {"name": "HIMANSHU GANGWAR", "sl": 6, "cl": 4, "el": 13},
        {"name": "ASHA ARUN GURNULE", "sl": 2.5, "cl": 1.5, "el": 4},
        {"name": "SAGAR SUBHASH CHAWARE", "sl": 4, "cl": 3, "el": 12},
        {"name": "AVINASH AMBADAS CHAVAN", "sl": 3, "cl": 3, "el": 12},
        {"name": "SANI BHARATI", "sl": 6, "cl": 4, "el": 13},
        {"name": "BHOPAL SINGH", "sl": 5, "cl": 4, "el": 13},
        {"name": "SHREYANSH AHIRWAR", "sl": 6, "cl": 4, "el": 13},
        {"name": "DEEPIKA", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANJUSHA SUNIL GAWANDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "SACHIN ARUN PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SAWAN KUMAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "LAKHAN PACHORE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NITIN NARAYAN MOGER", "sl": 0, "cl": 0, "el": 0},
        {"name": "KUNWAR SINGH", "sl": 0, "cl": 0, "el": 0},
        {"name": "MANJUNATH N PUJARI", "sl": 0, "cl": 0, "el": 0},
        {"name": "SANJAY S KADAM", "sl": 1, "cl": 1, "el": 3},
        {"name": "HARISH HANUMANTAPPA HALAVAGAL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHRUTI", "sl": 5.5, "cl": 4, "el": 12},
        {"name": "MANISHA DHIRAJ WAVHALE", "sl": 1.5, "cl": 4, "el": 12},
        {"name": "SAHIL MASRAM", "sl": 0, "cl": 0, "el": 0},
        {"name": "ATUL CHANDU PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SUSHMA SANEKAR", "sl": 4.5, "cl": 4, "el": 8},
        {"name": "ROHIT SHIVNARAYAN", "sl": 3, "cl": 3, "el": 12},
        {"name": "TAI DILIP GAIKWAD", "sl": 0, "cl": 0, "el": 0},
        {"name": "ASHTSHILA KAMBLE", "sl": 3.5, "cl": 4, "el": 9},
        {"name": "SHUBHANGI LAXMAN SHELAKE", "sl": 6.5, "cl": 4, "el": 12},
        {"name": "ANIL SURESH PATIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "HARISH SALANI", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHAM GOVINDARAO GAIKWAD", "sl": 0, "cl": 0, "el": 0},
        {"name": "KALPANA RAMESH BORKAR", "sl": 3.5, "cl": 4, "el": 12},
        {"name": "BASANT", "sl": 6, "cl": 4, "el": 11},
        {"name": "NITIN CHOUHAN", "sl": 0, "cl": 0, "el": 0},
        {"name": "YOGITA J. DHALE", "sl": 2, "cl": 2, "el": 8},
        {"name": "MAHESH CHANDRA", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAJESH DARBAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "SHANI SONI", "sl": 0, "cl": 0, "el": 0},
        {"name": "ARTI RAJENDRA TORVEKAR", "sl": 1.5, "cl": 3.5, "el": 10},
        {"name": "BIMLA DEVI", "sl": 0, "cl": 0, "el": 0},
        {"name": "LEELAVATHI", "sl": 1, "cl": 1, "el": 9},
        {"name": "MAHESH GAWANDE", "sl": 0, "cl": 0, "el": 0},
        {"name": "DEEPENDRA MUKHIYA", "sl": 4.5, "cl": 3.5, "el": 9},
        {"name": "AMIT RATHOD", "sl": 4, "cl": 2, "el": 9},
        {"name": "NILESH UMASHANKAR SONI", "sl": 5, "cl": 4, "el": 11},
        {"name": "SHANKARGOUDA KARIYAPPAGAOUDA", "sl": 0, "cl": 0, "el": 0},
        {"name": "DURGESHWAR SHANKAR KAMBLE", "sl": 0, "cl": 0, "el": 0},
        {"name": "ACHHARI DEVI", "sl": 4, "cl": 3, "el": 7},
        {"name": "AMBIKA SANTOSH CHINTAWAR", "sl": 1, "cl": 1, "el": 6},
        {"name": "RITESH VIJAY DESHMUKH", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "KISHOR DNYANESHWAR INGLE", "sl": 3.5, "cl": 2.5, "el": 9},
        {"name": "MANJUSHA SANTOSH MARKAND", "sl": 2.5, "cl": 3.5, "el": 10},
        {"name": "REKHA", "sl": 3.5, "cl": 1.5, "el": 9},
        {"name": "SHRISHAIL YALLAPPA JALAGERI", "sl": 0, "cl": 0, "el": 0},
        {"name": "YUVRAJ GANESH GURAV", "sl": 2, "cl": 2, "el": 9},
        {"name": "PANKAJ SANTOSH MOHITE", "sl": 0, "cl": 0, "el": 0},
        {"name": "YOGESH CHOUDHARI", "sl": 5, "cl": 3, "el": 9},
        {"name": "MANISHA R. UMREDKAR", "sl": 2.5, "cl": 1.5, "el": 9},
        {"name": "JAYA", "sl": 1, "cl": 1, "el": 4},
        {"name": "GANGA DEVI", "sl": 5, "cl": 3, "el": 9},
        {"name": "SAHIL", "sl": 0, "cl": 0, "el": 0},
        {"name": "SATYAJIT PATHAK", "sl": 0, "cl": 0, "el": 0},
        {"name": "ARYAN KONDIYA", "sl": 0, "cl": 0, "el": 0},
        {"name": "MOHD. NASIR BHAT", "sl": 0, "cl": 0, "el": 0},
        {"name": "KRISHNA SHELKE", "sl": 0, "cl": 0, "el": 0},
        {"name": "NAMRATA SANDIP SHORSATH", "sl": 3, "cl": 2, "el": 6},
        {"name": "MOHD. IQBAL RATHER", "sl": 3, "cl": 2, "el": 7},
        {"name": "MUZAMIL RAFIQ", "sl": 1.5, "cl": 0.5, "el": 6},
        {"name": "VISHAL DHANRAJ MADAVI", "sl": 3.5, "cl": 1.5, "el": 8},
        {"name": "TANVEER AHMAD BEIGH", "sl": 0, "cl": 0, "el": 0},
        {"name": "RAKESH MUTAGAR", "sl": 4, "cl": 1, "el": 9},
        {"name": "SUMIT", "sl": 2.5, "cl": 1.5, "el": 7},
        {"name": "ANURAG SEN", "sl": 4, "cl": 3, "el": 9},
        {"name": "SHAKIR MOHI U DIN DAR", "sl": 4, "cl": 2, "el": 7},
        {"name": "SUJANA NALINA KUMARI", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "ROBIN", "sl": 4.5, "cl": 2.5, "el": 8},
        {"name": "JAGDISH CHAND", "sl": 4, "cl": 2, "el": 7},
        {"name": "YASHMIN RIYAJ SHEIKH", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "LATA DEVI", "sl": 3, "cl": 1, "el": 4},
        {"name": "SANTOSHI AJAY YADAV", "sl": 2.5, "cl": 1.5, "el": 8},
        {"name": "AVINASH SANJAY SHEJWAL", "sl": 0, "cl": 0, "el": 0},
        {"name": "VIJAY LAXMI", "sl": 1.5, "cl": 2.5, "el": 7},
        {"name": "ARCHANA", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "MONIKA", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "TEJSWANI VILAS KOTGALE", "sl": 0, "cl": 0, "el": 0},
        {"name": "KAMAL NAIN", "sl": 4.5, "cl": 1.5, "el": 8},
        {"name": "NIRMALA SADHURAM DHEKWAR", "sl": 1.5, "cl": 0.5, "el": 7},
        {"name": "SANGITA RAJIV BODAKHE", "sl": 3.5, "cl": 2.5, "el": 8},
        {"name": "RAMESHWAR RAJU SHERE", "sl": 0, "cl": 0, "el": 0},
        {"name": "MOHAR SINGH", "sl": 3.5, "cl": 1.5, "el": 6},
        {"name": "VARSHA DEEPAK KAMBLE", "sl": 2.5, "cl": 1.5, "el": 3},
        {"name": "PRAMILA B KHARAT", "sl": 4, "cl": 2, "el": 7},
        {"name": "AASMA NASIR PATEL", "sl": 2, "cl": 1, "el": 6},
        {"name": "TRIPTA DEVI", "sl": 3.5, "cl": 1.5, "el": 6},
        {"name": "RITIK BHOSALE", "sl": 1, "cl": 1, "el": 3},
        {"name": "JATIN PAL", "sl": 3, "cl": 1, "el": 7},
        {"name": "AMAR RAWAT", "sl": 4, "cl": 2, "el": 7},
        {"name": "BASANTI THALWAL", "sl": 2.5, "cl": 1.5, "el": 6},
        {"name": "SHANKAR LAL KHAITWAS", "sl": 0, "cl": 0, "el": 0},
        {"name": "GEETA ETTINAMANI", "sl": 0.5, "cl": 0.5, "el": 3},
        {"name": "BASAVARAJ M DURAGANNANAVAR", "sl": 2.5, "cl": 1.5, "el": 6},
        {"name": "LAKSHMI NAGALAPUR", "sl": 2.5, "cl": 0.5, "el": 6},
        {"name": "VANITA GANESH BONDRE", "sl": 1.5, "cl": 1.5, "el": 6},
        {"name": "MOHIT GATHAIYA", "sl": 2, "cl": 1, "el": 5},
        {"name": "SAGAR NIVRUTTI KOKATE", "sl": 2.5, "cl": 1, "el": 5},
        {"name": "KEWAL KUMAR", "sl": 0, "cl": 0, "el": 0},
        {"name": "BHAGWAN BHIKAJI BAWANE", "sl": 3, "cl": 1, "el": 5},
        {"name": "DHRUV VEDHYA", "sl": 3, "cl": 1, "el": 5},
        {"name": "ABHISHEK GAJANAN MORE", "sl": 2, "cl": 1, "el": 5},
        {"name": "RAVI", "sl": 0, "cl": 0, "el": 0},
        {"name": "SRINIVASALU N", "sl": 1, "cl": 1, "el": 5},
        {"name": "NILESH PRAMOD KAPADE", "sl": 3, "cl": 1, "el": 5},
        {"name": "SUNITA VEDPRAKASH SHARMA", "sl": 2, "cl": 1, "el": 5},
        {"name": "SURAJ", "sl": 3, "cl": 1, "el": 5},
        {"name": "RUDRAKSH RAJ SHARMA", "sl": 0, "cl": 0, "el": 0},
        {"name": "VEDANT DEORE", "sl": 1, "cl": 1, "el": 5},
        {"name": "AMAR CHANDRA JATAV", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "GEETA JADAV", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "VIVEK LOHARE", "sl": 3, "cl": 1, "el": 5},
        {"name": "BABITA", "sl": 2.5, "cl": 1, "el": 5},
        {"name": "DEEPAK VERMA", "sl": 2.5, "cl": 1, "el": 5},
        {"name": "OMKAR BADEL", "sl": 0, "cl": 0, "el": 0},
        {"name": "REENA", "sl": 1.5, "cl": 0.75, "el": 3.75},
        {"name": "PRATIK GOPAL KHIRADE", "sl": 2.5, "cl": 1, "el": 5},
        {"name": "JANARDAN RAMCHANDRA NAGOSE", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "SUKHARAM PAWAR", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "ZAHIDA MAJEET", "sl": 0.5, "cl": 0.5, "el": 2.5},
        {"name": "PAVAN AIRANI", "sl": 2.5, "cl": 1, "el": 5},
        {"name": "ARTI KAHAR", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "SIDDHARTH VILAS JUVALE", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "ZAHIDA BEGUM", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "VYANKATESH NARAYAN", "sl": 1, "cl": 0.5, "el": 2.5},
        {"name": "AMARDEEP RAJAK", "sl": 1, "cl": 0.5, "el": 2.5},
    ]
